"""Pydantic v2 请求 / 响应模型（§5.5 API 契约）。

约定：
    * 所有 `Vo` 后缀为**响应**模型，`Create` / `Update` / `Request` 后缀为**请求**模型；
    * 金额在 API 层统一用**字符串「元」**（如 `"29.90"`），DB 层用整数「分」；
    * 时间统一 ISO8601 UTC 字符串；
    * 所有 Vo 提供 `from_model()` 类方法，从 ORM 对象构造（避免 ORM 对象直接外泄）。
"""

from __future__ import annotations

from app.schemas.asset import (
    AiTaskDetailVo,
    AiTaskResultVo,
    AiTaskVo,
    AssetRollbackRequest,
    AssetTagUpdate,
    AssetVo,
    BatchDownloadRequest,
)
from app.schemas.common import (
    IdVo,
    MoneyField,
    OkVo,
    PageQuery,
    cents_to_yuan,
    parse_money,
)
from app.schemas.inventory import (
    AutoOfflineRecordVo,
    InventoryAlertVo,
    InventoryConfigUpdate,
    InventoryConfigVo,
    InventorySnapshotVo,
    InventorySyncRequest,
    PriceSnapshotVo,
)
from app.schemas.listing import (
    CredentialCreate,
    CredentialRevealRequest,
    CredentialUpdate,
    CredentialVo,
    FillPriceItem,
    FillPriceRequest,
    ListingProductDetailVo,
    ListingProductVo,
    PlatformAccountAuthorizeRequest,
    PlatformAccountCreate,
    PlatformAccountVo,
    PublishTaskCreate,
    PublishTaskDetailVo,
    PublishTaskVo,
)
from app.schemas.mapping import (
    FillBackRequest,
    FillBackSku,
    MappingChangeLogVo,
    MappingConflictVo,
    MappingPendingVo,
    MappingStatsVo,
    MappingValidationConflict,
    MappingValidationMissing,
    MappingValidationVo,
    SkuMappingBatchRequest,
    SkuMappingCreate,
    SkuMappingUpdate,
    SkuMappingVo,
)
from app.schemas.order import (
    AfterSaleResponsibilityUpdate,
    AfterSaleVo,
    OrderActionRequest,
    OrderDetailVo,
    OrderExceptionVo,
    OrderItemVo,
    OrderMatchRequest,
    OrderSyncRequest,
    OrderVo,
    PurchaseOrderTrackingRequest,
    PurchaseOrderVo,
)
from app.schemas.source import (
    SourceProductDetailVo,
    SourceProductVo,
    SourceSkuVo,
    SupplierCreate,
    SupplierUpdate,
    SupplierVo,
)
from app.schemas.system import (
    AdapterSwitchRequest,
    AuditLogVo,
    FulfillmentAdapterConfigUpdate,
    FulfillmentAdapterVo,
    ScopeViolationHandleRequest,
    ScopeViolationVo,
    SettingUpdate,
    StatusBarVo,
    TaskRecordVo,
)

__all__ = [
    "AdapterSwitchRequest",
    "AfterSaleResponsibilityUpdate",
    "AfterSaleVo",
    "AiTaskDetailVo",
    "AiTaskResultVo",
    "AiTaskVo",
    "AssetRollbackRequest",
    "AssetTagUpdate",
    "AssetVo",
    "AuditLogVo",
    "AutoOfflineRecordVo",
    "BatchDownloadRequest",
    "CredentialCreate",
    "CredentialRevealRequest",
    "CredentialUpdate",
    "CredentialVo",
    "FillBackRequest",
    "FillBackSku",
    "FillPriceItem",
    "FillPriceRequest",
    "FulfillmentAdapterConfigUpdate",
    "FulfillmentAdapterVo",
    "IdVo",
    "InventoryAlertVo",
    "InventoryConfigUpdate",
    "InventoryConfigVo",
    "InventorySnapshotVo",
    "InventorySyncRequest",
    "ListingProductDetailVo",
    "ListingProductVo",
    "MappingChangeLogVo",
    "MappingConflictVo",
    "MappingPendingVo",
    "MappingStatsVo",
    "MappingValidationConflict",
    "MappingValidationMissing",
    "MappingValidationVo",
    "MoneyField",
    "OkVo",
    "OrderActionRequest",
    "OrderDetailVo",
    "OrderExceptionVo",
    "OrderItemVo",
    "OrderMatchRequest",
    "OrderSyncRequest",
    "OrderVo",
    "PageQuery",
    "PlatformAccountAuthorizeRequest",
    "PlatformAccountCreate",
    "PlatformAccountVo",
    "PriceSnapshotVo",
    "PublishTaskCreate",
    "PublishTaskDetailVo",
    "PublishTaskVo",
    "PurchaseOrderTrackingRequest",
    "PurchaseOrderVo",
    "ScopeViolationHandleRequest",
    "ScopeViolationVo",
    "SettingUpdate",
    "SkuMappingBatchRequest",
    "SkuMappingCreate",
    "SkuMappingUpdate",
    "SkuMappingVo",
    "SourceProductDetailVo",
    "SourceProductVo",
    "SourceSkuVo",
    "StatusBarVo",
    "SupplierCreate",
    "SupplierUpdate",
    "SupplierVo",
    "TaskRecordVo",
    "cents_to_yuan",
    "parse_money",
]
